default_platform(:ios)

platform :ios do
  lane :beta do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_API_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    match(
      type: "appstore",
      app_identifier: "com.nathanvans.picklerankings",
      api_key: api_key,
      readonly: false
    )

    build_app(
      workspace: "ios/App/App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      output_directory: "./build",
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APPLE_TEAM_ID']}"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
